### ISSUE TITLE
Add comment

### ISSUE THREAD

**Issue by antonioettorre** [wielinde/toggl_track_to_openproject#1]
It is possible to add also the capabilities to upload the comment using a separator?
For example using :  [OP#] : comment

**Comment by wielinde** [comment]
Sure, that is theoretically possible. Maybe a colon is not the best separator. I use it at times within work package titles. 

I do not use this integration anymore. With the next release of OpenProject 13.0 you can start and stop time tracking right on the work package.

**Comment by antonioettorre** [comment]
thanks, so i can wait for OpenProject 13.0
